In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
random_arr = np.random.rand(5, 5)
result = arr + random_arr
result = result * 2
dot_product = np.dot(arr, random_arr)

In [ ]:
import pandas as pd
data = {'nome': ['Alice', 'Bob', 'Charlie'],
        'eta': [25, 30, 35]}
df = pd.DataFrame(data)

ages = df['eta']
filtered_data = df[df['eta'] > 30]

In [ ]:
import matplotlib.pyplot as plt
# creazione di dati
x = [1, 2, 3, 4, 5]
y = [10, 12, 5, 8, 20]
plt.scatter(x, y)
plt.xlbale('Asse X')
plt.ylabel('Asse Y')
plt.title('Grafico a Dispersione')
plt.show()

In [ ]:
data = [3, 4, 2, 7, 5, 6, 8, 7, 6, 5, 4, 5, 6, 7, 4]

plt.hist(data, bins=5, color='blue', alpha=0.7)
plt.xlabel('Valore')
plt.ylabel('Frequenza')
plt.title('Istogramma')
plt.show()

In [5]:
vettore_colonna = np.array([1, 2, 3, 4, 5])
vettore_riga = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrice_zeri = np.zeros((3, 3))
matrice_identita = np.identity(3)
matrice_identita = np.eye(3)

In [6]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
mat_t = matrix.T
print(matrix)
print(mat_t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
A = np.array([[1,2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
somma = A + B
sott = A - B